site_name: PCM Documentation
site_description: Creating better PCM documentation, one function at a time.
site_url: ""
repo_url: https://www.github.com/youdoof/pcmdoc
repo_name: youdoof/pcmdoc

# edit_uri: ""

copyright: <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  icon:
    logo: material/file-document
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - content.action.view
    - navigation.top
    # - navigation.path
    - navigation.footer

# Markdown Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # Material for MkDocs Plugins


plugins:
  - privacy
  - search

extra:
  consent:
    title: Cookie Consent
    description: This website uses essential cookies to maintain your session and facilitate the connection to the documentation repository. No third-party tracking is used.
