site_name: PCM DOC
site_url: ""
repo_url: https://www.github.com/youdoof/pcmdoc
repo_name: youdoof/pcmdoc

# edit_uri: ""

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
  features:
    - content.code.copy
    - content.action.view

# Markdown Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
